# Generated by Django 5.2.5 on 2025-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='latitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='longitude',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='opening_hours',
            field=models.CharField(blank=True, help_text='مثلاً Mo-Fr 08:00-17:00', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='google_map_embed',
            field=models.TextField(blank=True, help_text='iframe embed code for Google Map'),
        ),
    ]
