# Generated by Django 5.2.5 on 2025-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_latitude_sitesetting_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
