# Generated by Django 5.2.5 on 2025-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesetting_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.CharField(blank=True, help_text='آدرس کامل (برای نمایش در تماس/فوتر)', max_length=255),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='google_map_embed',
            field=models.TextField(blank=True, help_text='کد iframe از Google Maps (Share → Embed a map)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='مختصات عرض جغرافیایی', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='مختصات طول جغرافیایی', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='meta_default_description',
            field=models.CharField(blank=True, help_text='توضیحات دیفالت برای متا', max_length=300),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='opening_hours',
            field=models.JSONField(blank=True, help_text='مثال: {"Mo-Fr": "08:00-17:00", "Sa": "09:00-13:00"}', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='phone',
            field=models.CharField(blank=True, help_text='شماره تلفن رسمی', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='BFGWebSite', help_text='نام نمایش\u200cداده\u200cشده سایت', max_length=200),
        ),
    ]
