# Generated by Django 5.2.5 on 2025-08-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-date'], 'verbose_name': 'تاریخچه قیمت', 'verbose_name_plural': 'تاریخچه قیمت\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, help_text='ALT متن برای سئو', max_length=250),
        ),
    ]
