# Generated by Django 5.2.5 on 2025-08-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(help_text='email or phone number or telegram id', max_length=200)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('telegram', 'Telegram')], default='email', max_length=20)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product')),
            ],
        ),
    ]
