# Generated by Django 5.2.5 on 2025-09-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_pricealert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'کیلوگرم'), ('branch', 'شاخه')], default='kg', max_length=10),
        ),
    ]
